default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %> 
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'spreedemo_development' %>

test:
  <<: *default
  database: spreedemo_test

dev:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
